### ISSUE TITLE
Unable to parse the value into type of array

### ISSUE THREAD

**Issue by pir8g33k** [azsec/scaf-azure-arm-templates#5]
Hi I'm getting issue on deployment i think on analytic rule severity and analytics rule tactics part. Please advise
https://azsec.azurewebsites.net/2021/12/18/detect-nsg-inbound-rule-updated-to-allow-all/

![image](https://user-images.githubusercontent.com/63558386/147760347-2b08d504-bb59-4ae1-9ee5-84485fc74d70.png)

**Comment by azsec** [comment]
@pir8g33k  The template is still valid. The problem you are having this issue is because when deploying this template via Azure Portal the `analyticsRuleTactics` type is converted to `String` while the actual type is `Array`. 

From the **Templates** page  you can edit the parameter file as re-deploy

```
        "analyticsRuleTactics": {
            "value": [
                "Collection"
            ]
        }
```

I barely recommend people to deploy ARM using Template deployment or going through Azure Portal. I would always tell them to use command-line to deploy an ARM template because with this way, you have more controls.

```bash
az group deployment create --name "deploy-nsg-rule-az-sentinel" \
                           --resource-group "azsec-corporate-rg" \
                           --template-file azuredeploy.json \
                           --parameters azuredeploy.parameters.json 
```

**Comment by pir8g33k** [comment]
i see awesome let me try and will revert you back, yap sure let me deploy with the command line as well, thank you
